packages:
  - packages/**
  - docs

ignoredBuiltDependencies:
  - esbuild
  - nx
  - sharp

linkWorkspacePackages: true
preferWorkspacePackages: true

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@elenajs/*"

onlyBuiltDependencies:
  - rs-module-lexer

overrides:
  glob@>=10.2.0 <10.5.0: ">=10.5.0"
