#
#    ██████████ ████
#   ░░███░░░░░█░░███
#    ░███  █ ░  ░███   ██████. ████████    ██████
#    ░██████    ░███  ███░░███░░███░░███  ░░░░░███
#    ░███░░█    ░███ ░███████  ░███ ░███   ███████
#    ░███ ░   █ ░███ ░███░░░   ░███ ░███  ███░░███
#    ██████████ █████░░██████  ████ █████░░████████
#   ░░░░░░░░░░ ░░░░░  ░░░░░░  ░░░░ ░░░░░  ░░░░░░░░
#
#   ░█ [ELENA]: Progressive Web Component Deploy

name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Install and Build
        run: |
          pnpm install
          pnpm docs:build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/.vitepress/dist
          clean: true
