#
#    ██████████ ████
#   ░░███░░░░░█░░███
#    ░███  █ ░  ░███   ██████. ████████    ██████
#    ░██████    ░███  ███░░███░░███░░███  ░░░░░███
#    ░███░░█    ░███ ░███████  ░███ ░███   ███████
#    ░███ ░   █ ░███ ░███░░░   ░███ ░███  ███░░███
#    ██████████ █████░░██████  ████ █████░░████████
#   ░░░░░░░░░░ ░░░░░  ░░░░░░  ░░░░ ░░░░░  ░░░░░░░░
#
#   ░█ [ELENA]: GitHub Pages Pull Request Preview

name: preview
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

      - name: Install Node.js
        if: github.event.action != 'closed'
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Install and Build
        if: github.event.action != 'closed'
        run: |
          pnpm install
          pnpm build
          pnpm --filter @elenajs/docs build
        env:
          ELENA_PATH: /pr-preview/pr-${{ github.event.number }}/
          ELENA_NOINDEX: true

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@ffa7509e91a3ec8dfc2e5536c4d5c1acdf7a6de9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source-dir: docs/dist
          pages-base-url: elenajs.com
          wait-for-pages-deployment: true
