#
#    ██████████ ████
#   ░░███░░░░░█░░███
#    ░███  █ ░  ░███   ██████. ████████    ██████
#    ░██████    ░███  ███░░███░░███░░███  ░░░░░███
#    ░███░░█    ░███ ░███████  ░███ ░███   ███████
#    ░███ ░   █ ░███ ░███░░░   ░███ ░███  ███░░███
#    ██████████ █████░░██████  ████ █████░░████████
#   ░░░░░░░░░░ ░░░░░  ░░░░░░  ░░░░ ░░░░░  ░░░░░░░░
#
#   ░█ [ELENA]: Progressive Web Component Tests

name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  build-and-test:
    if: "!startsWith(github.event.head_commit.message, '[publish]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Run test suites
        run: |
          pnpm install
          pnpm lint
          pnpm build
          pnpm test
          pnpm --filter @elenajs/docs build
